const data = [
        {
            "electronic": [
                {
                    "id": "1",
                    "link":"/electronic/phones",
                    "name_uz": "Telefonlar",
                    "name_oz": "Телефонлар",
                    "name_ru": "Телефоны",
                },
                {
                    "id": "2",
                    "link":"/electronic/computers",
                    "name_uz": "Komputerlar",
                    "name_oz": "Компютерлар",
                    "name_ru": "Компьютеры",
                },
                {
                    "id": "3",
                    "link":"/electronic/tv-video",
                    "name_uz": "Televizor va videotexnika",
                    "name_oz": "Тв ва видеотехника",
                    "name_ru": "Тв и видеотехника",
                },
                {
                    "id": "4",
                    "link":"/electronic/photo-video",
                    "name_uz": "Video va fototexnika",
                    "name_oz": "Видео ва фототехника",
                    "name_ru": "Видео и фототехника",
                },
                {
                    "id": "5",
                    "link":"/electronic/console",
                    "name_uz": "O'yin pristavkalari,o'yin, programmalar ",
                    "name_oz": "Уйин приставкалари, уйин, программалар",
                    "name_ru": "Игровые приставкиб игры, программы, ",
                },
                {
                    "id": "6",
                    "link":"/electronic/home",
                    "name_uz": "Uy texnikasi",
                    "name_oz": "Уй техникаси",
                    "name_ru": "Техника для дома",
                },
                {
                    "id": "7",
                    "link":"/electronic/kitchen",
                    "name_uz": "Oshxona texnikasi",
                    "name_oz": "Ошхона техникаси",
                    "name_ru": "Техника для кухни",
                },
                {
                    "id": "8",
                    "link":"/electronic/season-tech",
                    "name_uz": "Iqlim texnikasi",
                    "name_oz": "Иклим техникаси",
                    "name_ru": "Климатическое оборудование",
                },
                {
                    "id": "9",
                    "link":"/electronic/individual-care",
                    "name_uz": "Shaxsiy parvarish",
                    "name_oz": "Шахсий парвариш",
                    "name_ru": "Индивидуальный уход",
                },
                {
                    "id": "10",
                    "link":"/electronic/spare",
                    "name_uz": "Komplekt va ehtiyot qismlari",
                    "name_oz": "Комплект ва эхтиет кисмлари",
                    "name_ru": "Комплектующие и запчасти",
                },
                {
                    "id": "11",
                    "link":"/electronic/office",
                    "name_uz": "Ofis jihozlari, sarf mahsulotlari",
                    "name_oz": "Офис жихозлари ва сарф материаллари",
                    "name_ru": "Оргтехника и расходники",
                },
                {
                    "id": "12",
                    "link":"/electronic/other-electronics",
                    "name_uz": "Boshqa turdagi",
                    "name_oz": "Бошка турдаги",
                    "name_ru": "Другое",
                },

            ],
            "children": [
                {
                    "id": "1",
                    "link":"/children/children-toys",
                    "name_uz": "O'yinchoqlar",
                    "name_oz": "Уйинчоклар",
                    "name_ru": "Игрушки",
                },
                {
                    "id": "2",
                    "link":"/children/children-shoes",
                    "name_uz": "Kiyim, Oyoq kiyimlar",
                    "name_oz": "Кийимлар, Оек кийимлар",
                    "name_ru": "Одежда и обувь",
                },
                {
                    "id": "3",
                    "link":"/children/feeding",
                    "name_uz": "Taom va Ozuqa",
                    "name_oz": "Таом ва озука",
                    "name_ru": "Еда, Кормление",
                },
                {
                    "id": "4",
                    "link":"/children/hygiene",
                    "name_uz": "Bolalar gigiyenasi",
                    "name_oz": "Болалар гигиенаси",
                    "name_ru": "Детская гигиена",
                },
                {
                    "id": "5",
                    "link":"/children/school-preparement",
                    "name_uz": "Maktab jihozlari",
                    "name_oz": "Мактаб жихозлари",
                    "name_ru": "товары для школы",
                },
                {
                    "id": "6",
                    "link":"/children/art",
                    "name_uz": "San'at / hobbi",
                    "name_oz": "Санъат, хобби",
                    "name_ru": "творчество и хобби",
                },
                {
                    "id": "7",
                    "link":"/children/children-cart",
                    "name_uz": "Kolyaska va o'rindiq",
                    "name_oz": "Коляска ва уриндик",
                    "name_ru": "коляски / кресла",
                },
                {
                    "id": "8",
                    "link":"/children/children-room",
                    "name_uz": "Bolalar xonasi",
                    "name_oz": "Болалар хонаси",
                    "name_ru": "детская комната",
                },
                {
                    "id": "9",
                    "link":"/children/sport",
                    "name_uz": "Sport va dam olish",
                    "name_oz": "Спорт ва дам олиш",
                    "name_ru": "спорт и отдых",
                },

                {
                    "id": "10",
                    "link":"/children/other-goods-for-children",
                    "name_uz": "Boshqa turdagi",
                    "name_oz": "Бошка турдаги",
                    "name_ru": "Другое",
                },

            ],
            "transport": [
                {
                    "id": "1",
                    "link":"/transport/car",
                    "name_uz": "Yengil avtomashinalar",
                    "name_oz": "Енгил автомашиналар",
                    "name_ru": "Легковые автомобили",
                },
                {
                    "id": "2",
                    "link":"/transport/spare-parts",
                    "name_uz": "Yengil mashina ehtiyot qismlari",
                    "name_oz": "Енгил автомашиналар кисмлари",
                    "name_ru": "Запчасти, аксессуары для легковых автомобилей",
                },
                {
                    "id": "3",
                    "link":"/transport/truck",
                    "name_uz": "Yuk mashinalari",
                    "name_oz": "Юк машиналари",
                    "name_ru": "Грузовые автомобили",
                },
                {
                    "id": "4",
                    "link":"/transport/truck-spare",
                    "name_uz": "Yuk mashina ehtiyot qismlari",
                    "name_oz": "Юк машина эхтиет кисмлари",
                    "name_ru": "Запчасти грузовых автомобилей",
                },
                {
                    "id": "5",
                    "link":"/transport/bus",
                    "name_uz": "Avtobus va mikroavtobuslar",
                    "name_oz": "Автобус, микроавтобуслар",
                    "name_ru": "Автобус, микроавтобусы",
                },
                {
                    "id": "6",
                    "link":"/transport/bus-parts",
                    "name_uz": "Avtobus,mikroavtobus ehtiyot qismlari",
                    "name_oz": "Автобус, микроавтобус кисмлари",
                    "name_ru": "Запчасти автобус, микроавтобусов",
                },
                {
                    "id": "7",
                    "link":"/transport/special-transport",
                    "name_uz": "Maxsus texnika, transport",
                    "name_oz": "Махсус техника транспорт",
                    "name_ru": "Спецтехника, спецтранспорт",
                },
                {
                    "id": "8",
                    "link":"/transport/special-equipment",
                    "name_uz": "Maxsus texnika ehtiyot qismlari",
                    "name_oz": "Махсус техника кисмлари",
                    "name_ru": "Запчасти спецтехники",
                },
                {
                    "id": "9",
                    "link":"/transport/moto",
                    "name_uz": "Mototransport",
                    "name_oz": "Мототранспорт",
                    "name_ru": "Мототранспорт",
                },
                {
                    "id": "10",
                    "link":"/transport/moto-parts",
                    "name_uz": "Mototransport ehtiyot qismlari",
                    "name_oz": "Мототранспорт кисмлари",
                    "name_ru": "Запчасти мототранспорта ",
                },
                {
                    "id": "11",
                    "link":"/transport/tires",
                    "name_uz": "G'ildirak , shina va disklar",
                    "name_oz": "Гилдирак, шина ва дисклар",
                    "name_ru": "Колеса, шины и диски",
                },
                {
                    "id": "12",
                    "link":"/transport/agricultural-machinery",
                    "name_uz": "Qishloq xo'jalik texnikasi",
                    "name_oz": "Кишлок хужалик техникаси",
                    "name_ru": "Агро Сельхоз техника",
                },
                {
                    "id": "13",
                    "link":"/transport/agricultural-parts",
                    "name_uz": "Qishloq xo'jalik texnikasi qismlari",
                    "name_oz": "Кишлок хужалик техникаси кисмлари",
                    "name_ru": "Запчасти агро сельхоз техники",
                },
                {
                    "id": "14",
                    "link":"/transport/trailer",
                    "name_uz": "Tirkama va boshqa turdagi transportlar",
                    "name_oz": "Тиркама ва бошка турдаги транспортлар",
                    "name_ru": "Прицепи, другие виды транспорта",
                },
                {
                    "id": "15",
                    "link":"/transport/water-transport",
                    "name_uz": "Suv transporti",
                    "name_oz": "Сув транспорти",
                    "name_ru": "Водяной транспорт",
                },
                {
                    "id": "16",
                    "link":"/transport/other-goods-for-transport",
                    "name_uz": "Boshqa turdagi transport ehtiyot qismlari",
                    "name_oz": "Бошка турдаги транспорт эхтиет кисмлари",
                    "name_ru": "Запчасти для других транспортов",
                },

            ],
            "services": [
                {
                    "id": "1",
                    "link":"/services/it",
                    "name_uz": "Kompyuter, IT xizmatlari",
                    "name_oz": "Компютер ва IT хизматлари",
                    "name_ru": "Компьютеры / IT услуги",
                },
                {
                    "id": "2",
                    "link":"/services/jurisdiction",
                    "name_uz": "Yuridik xizmatlar",
                    "name_oz": "Юридик хизматлар",
                    "name_ru": "Юридические услуги",
                },
                {
                    "id": "3",
                    "link":"/services/school-mentor",
                    "name_uz": "Ta'lim sohasi va repetirorlik",
                    "name_oz": "Таълим сохаси ва репетиторлик",
                    "name_ru": "Обучение и репетиторы",
                },
                {
                    "id": "4",
                    "link":"/services/repair",
                    "name_uz": "Texnika ta'mirlash va o'rnatish",
                    "name_oz": "Техника таъмирлаш ва урнатиш",
                    "name_ru": "Ремонт и установка техники",
                },
                {
                    "id": "4",
                    "link":"/services/medical",
                    "name_uz": "Meditsina va farm xizmatlar",
                    "name_oz": "Медицина, фарм хизматлар",
                    "name_ru": "Медицинские, фарм услуги",
                },
                {
                    "id": "5",
                    "link":"/services/sport-fit",
                    "name_uz": "Sport va fitnes",
                    "name_oz": "Спорт ва фитнес",
                    "name_ru": "Спорт / фитнес услуги",
                },
                {
                    "id": "6",
                    "link":"/services/beauty-health",
                    "name_uz": "Go'zallik va sog'liq",
                    "name_oz": "Гузаллик ва соглик",
                    "name_ru": "Красота / здоровье",
                },
                {
                    "id": "7",
                    "link":"/services/building-improvement",
                    "name_uz": "Qurilish , Ta'mirlash",
                    "name_oz": "Курилиш / таъмирлаш",
                    "name_ru": "Ремонт / строительство",
                },
                {
                    "id": "8",
                    "link":"/services/delivery",
                    "name_uz": "Tashish, yetkazib berish",
                    "name_oz": "Ташиш, етказиб бериш",
                    "name_ru": "Перевозки / курьеры",
                },
                {
                    "id": "9",
                    "link":"/services/safety",
                    "name_uz": "Qo'riqlash va xavfsizlik",
                    "name_oz": "Куриклаш, хавфсизлик",
                    "name_ru": "Охрана, безопасность",
                },
                {
                    "id": "10",
                    "link":"/services/event",
                    "name_uz": "Tadbirlar tashkil etish",
                    "name_oz": "Тадбирлар ташкил этиш",
                    "name_ru": "Организация мероприятий",
                },

                {
                    "id": "11",
                    "link":"/services/cleaning",
                    "name_uz": "Klining, tozalash ishlari",
                    "name_oz": "Клининг, тозалаш ишлари",
                    "name_ru": "Клининг / уборка",
                },
                {
                    "id": "12",
                    "link":"/services/other-electronics",
                    "name_uz": "Foto, video, audio xizmatlar",
                    "name_oz": "Фото, видео, аудио хизматлар",
                    "name_ru": "Фото / видео / аудио услуги",
                },
                {
                    "id": "13",
                    "link":"/services/tourism",
                    "name_uz": "Turizm, sayohat",
                    "name_oz": "Туризм, саехат",
                    "name_ru": "Туризм / путешествия",
                },
                {
                    "id": "14",
                    "link":"/services/auto-repair",
                    "name_uz": "Transport , avto ta'mirlash",
                    "name_oz": "Транспорт, авто таъмирлаш",
                    "name_ru": "Ремонт транспорта и авто",
                },
                {
                    "id": "15",
                    "link":"/services/other-electronics",
                    "name_uz": "Hayvonlarga xizmat ko'rsatish",
                    "name_oz": "Хайвонларга хизмат курсатиш",
                    "name_ru": "Услуги для животных",
                },
                {
                    "id": "16",
                    "link":"/services/other-",
                    "name_uz": "Boshqa turdagi xizmatlar",
                    "name_oz": "Бошка турдаги хизматлар",
                    "name_ru": "Другие услуги",
                },

            ],
            "job": [
                {
                    "id": "1",
                    "link":"/job/study-science",
                    "name_uz": "Fan va ta'lim",
                    "name_oz": "Фан ва таълим",
                    "name_ru": "Образование, наука",
                },
                {
                    "id": "2",
                    "link":"/job/sales",
                    "name_uz": "Savdo-sotiq , tijorat",
                    "name_oz": "Тижорат , савдо-сотик",
                    "name_ru": "Торговля, Продажа",
                },
                {
                    "id": "3",
                    "link":"/job/transport",
                    "name_uz": "Logistika va T.I.F.",
                    "name_oz": "Логистика ва Т.И.Ф.",
                    "name_ru": "Логистика и ВЭД",
                },
                {
                    "id": "4",
                    "link":"/job/building",
                    "name_uz": "Qurilish, ta'mirlash",
                    "name_oz": "Курилиш, таъмирлаш",
                    "name_ru": "Строительство , ремонт",
                },
                {
                    "id": "5",
                    "link":"/job/restaurant",
                    "name_uz": "Kafe va restoranlar",
                    "name_oz": "Кафе ва ресторанлар",
                    "name_ru": "Рестораны , кафе ",
                },
                {
                    "id": "6",
                    "link":"/job/jurisdiction",
                    "name_uz": "Yurisprudensiya",
                    "name_oz": "Юриспруденция",
                    "name_ru": "Юриспруденция",
                },
                {
                    "id": "7",
                    "link":"/job/security",
                    "name_uz": "Qo'riqlash, xavfsizlik",
                    "name_oz": "Куриклаш, хавфсизлик",
                    "name_ru": "Охрана / безопасность",
                },
                {
                    "id": "8",
                    "link":"/job/house",
                    "name_uz": "Uy ishchilari, enagalar",
                    "name_oz": "Уй ишчилари, энагалар",
                    "name_ru": "Няни, сиделки, домашний персонал",
                },
                {
                    "id": "9",
                    "link":"/job/property",
                    "name_uz": "Ko'chmas mulk",
                    "name_oz": "Кучмас мулк",
                    "name_ru": "Недвижимость",
                },
                {
                    "id": "10",
                    "link":"/job/fitness",
                    "name_uz": "Fitness va sport",
                    "name_oz": "Фитнес ва спорт",
                    "name_ru": "Фитнес, спорт",
                },
                {
                    "id": "11",
                    "link":"/job/tourism",
                    "name_uz": "Dam olish va turizm",
                    "name_oz": "Дам олиш ва туризм",
                    "name_ru": "Туризм, отдых",
                },
                {
                    "id": "12",
                    "link":"/job/medicine-pharmacy",
                    "name_uz": "Meditsina va farmatsiya",
                    "name_oz": "Медицина ва фармация",
                    "name_ru": "Медицина, фармация",
                },
                {
                    "id": "13",
                    "link":"/job/art",
                    "name_uz": "San'at va madaniyat",
                    "name_oz": "Санъат ва маданият",
                    "name_ru": "Искусство, культура",
                },
                {
                    "id": "14",
                    "link":"/job/it",
                    "name_uz": "IT, kompyuter, telekom",
                    "name_oz": "IT, компютер, телеком",
                    "name_ru": "IT, компьютеры, телеком",
                },
                {
                    "id": "15",
                    "link":"/job/",
                    "name_uz": "Menedjment va boshqaruv",
                    "name_oz": "Менеджемент ва бошкарув",
                    "name_ru": "Менеджмент и управление",
                },
                {
                    "id": "16",
                    "link":"/job/marketing",
                    "name_uz": "Marketing, reklama, PR",
                    "name_oz": "Маркетинг, реклама, PR",
                    "name_ru": "Маркетинг, реклама, PR",
                },
                {
                    "id": "17",
                    "link":"/job/manufacturing",
                    "name_uz": "Ishlab chiqarish, sanoat",
                    "name_oz": "Ишлаб чикариш, Саноат",
                    "name_ru": "Производство, промышленность",
                },
                {
                    "id": "18",
                    "link":"/job/student",
                    "name_uz": "Studentlar",
                    "name_oz": "Студентлар",
                    "name_ru": "Студенты",
                },
                {
                    "id": "19",
                    "link":"/job/service",
                    "name_uz": "Maishiy xizmat",
                    "name_oz": "Маиший хизмат",
                    "name_ru": "Сервис и быт",
                },
                {
                    "id": "20",
                    "link":"/job/career",
                    "name_uz": "Karyera boshlash",
                    "name_oz": "Карера бошлаш",
                    "name_ru": "Начало карьеры",
                },
                {
                    "id": "21",
                    "link":"/job/media",
                    "name_uz": "Media va nashriyot",
                    "name_oz": "Медиа ва нашриет",
                    "name_ru": "СМИ и издательство",
                },
                {
                    "id": "22",
                    "link":"/job/media",
                    "name_uz": "Kotibiyat, ish yuritish",
                    "name_oz": "Котибият, иш юритиш",
                    "name_ru": "Секретариат, делопроизводство",
                },
                {
                    "id": "23",
                    "link":"/job/finance",
                    "name_uz": "Moliya, iqtisodiyot",
                    "name_oz": "Молия, иктисодиет",
                    "name_ru": "Финансы, экономика",
                },
                {
                    "id": "24",
                    "link":"/job/beauty-fashion",
                    "name_uz": "Go'zallik va moda",
                    "name_oz": "Гузаллик ва мода",
                    "name_ru": "Красота и мода",
                },
                {
                    "id": "24",
                    "link":"/job/",
                    "name_uz": "Qisman bandlik",
                    "name_oz": "Кисман бандлик",
                    "name_ru": "Частичная занятость",
                },
                {
                    "id": "24",
                    "link":"/job/other-jobs",
                    "name_uz": "Boshqa turdagi",
                    "name_oz": "Бошка турдаги",
                    "name_ru": "Другие",
                },
            ],
            "charity": [
                {
                    "id": "1",
                    "link":"/charity/charity",
                    "name_uz": "Xayriya",
                    "name_oz": "Хайрия",
                    "name_ru": "Благотворительность",
                },
                {
                    "id": "2",
                    "link":"/charity/as-a-gift",
                    "name_uz": "Tekinga beraman",
                    "name_oz": "Текинга бераман",
                    "name_ru": "Отдам даром",
                },
            ],
            "property": [
                {
                    "id": "1",
                    "link":"/property/flats",
                    "name_uz": "Kvartiralar ijarasi",
                    "name_oz": "Квартиралар ижараси",
                    "name_ru": "Квартиры в аренду",
                },
                {
                    "id": "2",
                    "link":"/property/day-flats",
                    "name_uz": "Kunlik ijara",
                    "name_oz": "Кунлик ижара",
                    "name_ru": "Квартиры посуточно",
                },
                {
                    "id": "3",
                    "link":"/property/houses",
                    "name_uz": "Uy, kotedj, dala hovli ",
                    "name_oz": "Уй, коттедж, дала ховли",
                    "name_ru": "Дома / дачи / коттеджи",
                },
                {
                    "id": "4",
                    "link":"/property/hotels",
                    "name_uz": "Mehmonxona, otel",
                    "name_oz": "Мехмонхона, отел",
                    "name_ru": "Гостиницы, Отели",
                },
                {
                    "id": "5",
                    "link":"/property/room",
                    "name_uz": "Xonalar",
                    "name_oz": "Хоналар",
                    "name_ru": "Комнаты",
                },
                {
                    "id": "6",
                    "link":"/property/commercial-use",
                    "name_uz": "Tijorat xona va binolari",
                    "name_oz": "Тижорат хона ва бинолари",
                    "name_ru": "Коммерческая недвижимость",
                },
                {
                    "id": "7",
                    "link":"/property/area",
                    "name_uz": "Yer maydonlari",
                    "name_oz": "Ер майдонлари",
                    "name_ru": "Земельные участки",
                },
                {
                    "id": "8",
                    "link":"/property/garage",
                    "name_uz": "Garajlar",
                    "name_oz": "Гаражлар",
                    "name_ru": "Гаражи",
                },
                {
                    "id": "9",
                    "link":"/property/others",
                    "name_uz": "Boshqa turdagi",
                    "name_oz": "Бошка турдаги",
                    "name_ru": "Другое",
                },
            ],
            "animals": [
                {
                    "id": "1",
                    "link":"/animals/dogs",
                    "name_uz": "Itlar",
                    "name_oz": "Итлар",
                    "name_ru": "Собаки",
                },
                {
                    "id": "2",
                    "link":"/animals/cats",
                    "name_uz": "Mushuklar",
                    "name_oz": "Мушуклар",
                    "name_ru": "Кошки",
                },
                {
                    "id": "3",
                    "link":"/animals/farm",
                    "name_uz": "Xo'jalik hayvonlari",
                    "name_oz": "Хужалик хайвонлари",
                    "name_ru": "Сельхоз животные",
                },
                {
                    "id": "4",
                    "link":"/animals/birds",
                    "name_uz": "Qushlar",
                    "name_oz": "Кушлар",
                    "name_ru": "Птицы",
                },
                {
                    "id": "5",
                    "link":"/animals/aquarium",
                    "name_uz": "Akvarium",
                    "name_oz": "Аквариум",
                    "name_ru": "Аквариум",
                },
                {
                    "id": "6",
                    "link":"/animals/reptiles",
                    "name_uz": "Reptiliyalar",
                    "name_oz": "Рептилиялар",
                    "name_ru": "Рептилии",
                },
                {
                    "id": "7",
                    "link":"/animals/goods-for-animals",
                    "name_uz": "Hayvonlar uchun maxsulotlar",
                    "name_oz": "Хайвонлар учун махсулотлар ",
                    "name_ru": "Товары для животных",
                },
                {
                    "id": "8",
                    "link":"/animals/feeding-animals",
                    "name_uz": "Hayvonlar uchun ozuqalar",
                    "name_oz": "Хайвонлар учун озукалар ",
                    "name_ru": " Еда для животных",
                },
                {
                    "id": "9",
                    "link":"/animals/others",
                    "name_uz": "Boshqa turdagi",
                    "name_oz": "Бошка турлар",
                    "name_ru": "Другие животные",
                },
            ],
            "business": [
                {
                    "id": "1",
                    "link":"/business/selling-business",
                    "name_uz": "Tayyor biznes",
                    "name_oz": "Тайер бизнес",
                    "name_ru": "Готовый бизнес",
                },
                {
                    "id": "2",
                    "link":"/business/equipment",
                    "name_uz": "Uskunalar",
                    "name_oz": "Ускуналар",
                    "name_ru": "Оборудования",
                },
                {
                    "id": "3",
                    "link":"/business/partner-finance",
                    "name_uz": "Moliya / hamkorlik",
                    "name_oz": "Молия / хамкорлик",
                    "name_ru": "Финансы / Партнерство",
                },
                {
                    "id": "4",
                    "link":"/business/raw",
                    "name_uz": "Xom ashyo / tovarlar",
                    "name_oz": "Хом ашё / товарлар",
                    "name_ru": "Сырье / Товары",
                },
                {
                    "id": "5",
                    "link":"/business/others",
                    "name_uz": "Boshqalar",
                    "name_oz": "Бошкалар",
                    "name_ru": "Другие",
                },
            ],
            "style-fashion": [
                {
                    "id": "1",
                    "link":"/style-fashion/clothes",
                    "name_uz": "Kiyim-kechak",
                    "name_oz": "Кийим-кечак",
                    "name_ru": "Одежда и обувь",
                },
                {
                    "id": "2",
                    "link":"/style-fashion/watches",
                    "name_uz": "Qo'l soatlari",
                    "name_oz": "Кул соатлари",
                    "name_ru": "Часы",
                },
                {
                    "id": "3",
                    "link":"/style-fashion/accessories",
                    "name_uz": "Aksessuarlar",
                    "name_oz": "Аксессуарлар",
                    "name_ru": "Аксессуары",
                },
                {
                    "id": "4",
                    "link":"/style-fashion/presents",
                    "name_uz": "Sovg'alar",
                    "name_oz": "Совгалар",
                    "name_ru": "Подарки",
                },
                {
                    "id": "5",
                    "link":"/style-fashion/beauty",
                    "name_uz": "Go'zallik-salomatlik",
                    "name_oz": "Гузаллик, саломатлик",
                    "name_ru": "Красота, здоровье",
                },
                {
                    "id": "6",
                    "link":"/style-fashion/others",
                    "name_uz": "Boshqa tovarlar",
                    "name_oz": "Бошкал товарлар",
                    "name_ru": "Другие товары",
                },
            ],
            "house": [
                {
                    "id": "2",
                    "link":"/house/furniture",
                    "name_uz": "Mebel va interyer",
                    "name_oz": "Мебел ва  интерьер",
                    "name_ru": "Мебель и интерьер",
                },
                {
                    "id": "1",
                    "link":"/house/food",
                    "name_uz": "Oziq-ovqat, ichimliklar",
                    "name_oz": "Озик-овкат, ичимликлар",
                    "name_ru": "Продукты питания, Напитки",
                },
                {
                    "id": "3",
                    "link":"/house/kitchen-goods",
                    "name_uz": "Oshxona jihozlari va idishlar",
                    "name_oz": "Ошхона жихозлари ва идишлар",
                    "name_ru": "Посуда и товары для кухни",
                },
                {
                    "id": "4",
                    "link":"/house/building-tools",
                    "name_uz": "Qurilish va ta'mir tovarlari",
                    "name_oz": "",
                    "name_ru": "Товары для строительства, ремонта"
                },
                {
                    "id": "5",
                    "link":"/house/plants",
                    "name_uz": "O'simliklar",
                    "name_oz": "Усимликлар",
                    "name_ru": "Растения",
                },
                {
                    "id": "7",
                    "link":"/house/tools",
                    "name_uz": "Bog' va uy uskunalari",
                    "name_oz": "Бог ва уй Ускуналари",
                    "name_ru": "Садовый, Хозяйственный инвентарь",
                },
                {
                    "id": "8",
                    "link":"/house/others",
                    "name_uz": "Boshqa turdagi tovarlar",
                    "name_oz": "Бошка турдаги товарлар",
                    "name_ru": "Другие товары",
                },
            ],
            "hobbies": [
                {
                    "id": "1",
                    "link":"/hobbies/tickets",
                    "name_uz": "Biletlar, sayohat",
                    "name_oz": "Билетлар, саехат",
                    "name_ru": "Билеты и путешествия",
                },
                {
                    "id": "2",
                    "link":"/hobbies/bicycle",
                    "name_uz": "Velosipedlar",
                    "name_oz": "Велосипедлар",
                    "name_ru": "Велосипеды",
                },
                {
                    "id": "3",
                    "link":"/hobbies/books",
                    "name_uz": "Kitob va jurnallar",
                    "name_oz": "Китоб ва журналлар",
                    "name_ru": "Книги и журналы",
                },
                {
                    "id": "4",
                    "link":"/hobbies/antique",
                    "name_uz": "Kolleksiya, antikvariat",
                    "name_oz": "Коллексия, антиквариат",
                    "name_ru": "Коллекционирование, Антиквариат",
                },
                {
                    "id": "5",
                    "link":"/hobbies/instrumental",
                    "name_uz": "Musiqa asboblari",
                    "name_oz": "Мусика асбоблари",
                    "name_ru": "Музыкальные инструменты",
                },
                {
                    "id": "6",
                    "link":"/hobbies/fishing",
                    "name_uz": "Ov, baliq ovi",
                    "name_oz": "Ов, балик овлаш",
                    "name_ru": "Охота и рыбалка",
                },
                {
                    "id": "7",
                    "link":"/hobbies/sport-rest",
                    "name_uz": "Sport va dam",
                    "name_oz": "Спорт ва дам",
                    "name_ru": "Спорт и отдых",
                },
                {
                    "id": "8",
                    "link":"/hobbies/others",
                    "name_uz": "Boshqalar",
                    "name_oz": "Бошкалар",
                    "name_ru": "Другое",
                },
            ]
        }
    ]