const location = [
        {
            "samarkand": [
                {
                    "id": "1",
                    "name_uz": "Samarqand",
                    "name_oz": "Самарканд",
                    "name_ru": "Самарканд",
                },
                {
                    "id": "2",
                    "name_uz": "Payshanba",
                    "name_oz": "Пайшанба",
                    "name_ru": "Пайшанбе",
                },
                {
                    "id": "3",
                    "name_uz": "Oqtosh",
                    "name_oz": "Октош",
                    "name_ru": "Акташ",
                },
                {
                    "id": "4",
                    "name_uz": "Bulung'ur",
                    "name_oz": "Булунгур",
                    "name_ru": "Булунгур",
                },
                {
                    "id": "5",
                    "name_uz": "Chelak",
                    "name_oz": "Челак",
                    "name_ru": "Чилек",
                },
                {
                    "id": "6",
                    "name_uz": "Darband",
                    "name_oz": "Дарбанд",
                    "name_ru": "Дарбанд",
                },
                {
                    "id": "7",
                    "name_uz": "Jomboy",
                    "name_oz": "Жомбой",
                    "name_ru": "Джамбай",
                },
                {
                    "id": "8",
                    "name_uz": "Juma",
                    "name_oz": "Жума",
                    "name_ru": "Джума",
                },

                {
                    "id": "9",
                    "name_uz": "Guzalkent",
                    "name_oz": "Гузалкент",
                    "name_ru": "Гузалкент",
                },
                {
                    "id": "10",
                    "name_uz": "Gulobod",
                    "name_oz": "Гулобод",
                    "name_ru": "Гюлабад",
                },
                {
                    "id": "11",
                    "name_uz": "Ishtixon",
                    "name_oz": "Иштихон",
                    "name_ru": "Иштыхан",
                },
                {
                    "id": "12",
                    "name_uz": "Kattaqo'rg'on",
                    "name_oz": "Каттакургон",
                    "name_ru": "Каттакурган",
                },
                {
                    "id": "13",
                    "name_uz": "Qo'shrobod",
                    "name_oz": "Кушробод",
                    "name_ru": "Кушрабад",
                },
                {
                    "id": "14",
                    "name_uz": "Loyish",
                    "name_oz": "Лоиш",
                    "name_ru": "Лаиш",
                },
                {
                    "id": "15",
                    "name_uz": "Nurobod",
                    "name_oz": "Нуробод",
                    "name_ru": "Нурабад",
                },
                {
                    "id": "16",
                    "name_uz": "Payariq",
                    "name_oz": "Пайарик",
                    "name_ru": "Пайарык",
                },
                {
                    "id": "17",
                    "name_uz": "Toyloq",
                    "name_oz": "Тойлок",
                    "name_ru": "Тайлак",
                },
                {
                    "id": "18",
                    "name_uz": "Urgut",
                    "name_oz": "Ургут",
                    "name_ru": "Ургут",
                },
                {
                    "id": "19",
                    "name_uz": "Ziyodin",
                    "name_oz": "Зиедин",
                    "name_ru": "Зиадин",
                },

            ],
            "tashkent": [
                {
                    "id": "20",
                    "name_uz": "Toshkent",
                    "name_oz": "Тошкент",
                    "name_ru": "Ташкент",
                },
                {
                    "id": "21",
                    "name_uz": "Oqqo'rg'on",
                    "name_oz": "Аккурган",
                    "name_ru": "Аккурган",
                },
                {
                    "id": "22",
                    "name_uz": "Olmaliq",
                    "name_oz": "Алмалык",
                    "name_ru": "Алмалык",
                },
                {
                    "id": "23",
                    "name_uz": "Angren",
                    "name_oz": "Ангрен",
                    "name_ru": "Ангрен",
                },
                {
                    "id": "24",
                    "name_uz": "Ohangaron",
                    "name_oz": "Ахангаран",
                    "name_ru": "Ахангаран",
                },
                {
                    "id": "25",
                    "name_uz": "Bekobod",
                    "name_oz": "Бекабад",
                    "name_ru": "Бекабад",
                },
                {
                    "id": "26",
                    "name_uz": "Katta Chimyon",
                    "name_oz": "Большой Чимган",
                    "name_ru": "Большой Чимган",
                },
                {
                    "id": "27",
                    "name_uz": "Bo'ka",
                    "name_oz": "Бука",
                    "name_ru": "Бука",
                },

                {
                    "id": "28",
                    "name_uz": "Chorvoq",
                    "name_oz": "Чарвак",
                    "name_ru": "Чарвак",
                },
                {
                    "id": "29",
                    "name_uz": "Chinoz",
                    "name_oz": "Чиназ",
                    "name_ru": "Чиназ",
                },
                {
                    "id": "30",
                    "name_uz": "Chirchiq",
                    "name_oz": "Чирчик",
                    "name_ru": "Чирчик",
                },
                {
                    "id": "31",
                    "name_uz": "So'qoq",
                    "name_oz": "Cукок",
                    "name_ru": "Cукок",
                },
                {
                    "id": "32",
                    "name_uz": "Do'rmon",
                    "name_oz": "Дурмень",
                    "name_ru": "Дурмень",
                },
                {
                    "id": "33",
                    "name_uz": "Do'stobod",
                    "name_oz": "Дустабад",
                    "name_ru": "Дустабад",
                },
                {
                    "id": "34",
                    "name_uz": "Eshonguzar",
                    "name_oz": "Эшангузар",
                    "name_ru": "Эшангузар",
                },
                {
                    "id": "35",
                    "name_uz": "G'azalkent",
                    "name_oz": "Газалкент",
                    "name_ru": "Газалкент",
                },
                {
                    "id": "36",
                    "name_uz": "Gulbahor",
                    "name_oz": "Гульбахор",
                    "name_ru": "Гульбахор",
                },
                {
                    "id": "37",
                    "name_uz": "Iskandar",
                    "name_oz": "Искандар",
                    "name_ru": "Искандар",
                },
                {
                    "id": "38",
                    "name_uz": "Qorasuv",
                    "name_oz": "Карасу",
                    "name_ru": "Карасу",
                },
                {
                    "id": "39",
                    "name_uz": "Keles",
                    "name_oz": "Келес",
                    "name_ru": "Келес",
                },
                {
                    "id": "40",
                    "name_uz": "Qibray",
                    "name_oz": "Кибрай",
                    "name_ru": "Кибрай",
                },
                {
                    "id": "41",
                    "name_uz": "Koksaroy",
                    "name_oz": "Коксарай",
                    "name_ru": "Коксарай",
                },
                {
                    "id": "42",
                    "name_uz": "Krasnogorsk",
                    "name_oz": "Красногорск",
                    "name_ru": "Красногорск",
                },
                {
                    "id": "43",
                    "name_uz": "Mirobod",
                    "name_oz": "Мирабад",
                    "name_ru": "Мирабад",
                },
                {
                    "id": "44",
                    "name_uz": "Nazarbek",
                    "name_oz": "Назарбек",
                    "name_ru": "Назарбек",
                },
                {
                    "id": "45",
                    "name_uz": "Nurafshon (To'ytepa)",
                    "name_oz": "Нурафшан (Тойтепа)",
                    "name_ru": "Нурафшан (Тойтепа)",
                },
                {
                    "id": "46",
                    "name_uz": "Parkent",
                    "name_oz": "Паркент",
                    "name_ru": "Паркент",
                },

                {
                    "id": "47",
                    "name_uz": "Pskent",
                    "name_oz": "Пскент",
                    "name_ru": "Пскент",
                },
                {
                    "id": "48",
                    "name_uz": "Salar",
                    "name_oz": "Салар",
                    "name_ru": "Салар",
                },
                {
                    "id": "49",
                    "name_uz": "Tashmore",
                    "name_oz": "Ташморе",
                    "name_ru": "Ташморе",
                },
                {
                    "id": "50",
                    "name_uz": "Turkiston",
                    "name_oz": "Туркестан",
                    "name_ru": "Туркестан",
                },
                {
                    "id": "51",
                    "name_uz": "O'rtaovul",
                    "name_oz": "Уртааул",
                    "name_ru": "Уртааул",
                },
                {
                    "id": "52",
                    "name_uz": "Xojikent",
                    "name_oz": "Ходжикент",
                    "name_ru": "Ходжикент",
                },
                {
                    "id": "53",
                    "name_uz": "Yangiobod",
                    "name_oz": "Янгиабад",
                    "name_ru": "Янгиабад",
                },
                {
                    "id": "54",
                    "name_uz": "Yangibozor",
                    "name_oz": "Янгибазар",
                    "name_ru": "Янгибазар",
                },
                {
                    "id": "55",
                    "name_uz": "Yangiyo'l",
                    "name_oz": "Янгиюль",
                    "name_ru": "Янгиюль",
                },
                {
                    "id": "56",
                    "name_uz": "Zafar",
                    "name_oz": "Зафар",
                    "name_ru": "Зафар",
                },
                {
                    "id": "57",
                    "name_uz": "Zangiota",
                    "name_oz": "Зангиата",
                    "name_ru": "Зангиата",
                },

            ],
            "andijan": [
                {
                    "id": "58",
                    "name_uz": "Andijon",
                    "name_oz": "Андижон",
                    "name_ru": "Андижан",
                },
                {
                    "id": "59",
                    "name_uz": "Oqoltin",
                    "name_oz": "Околтин",
                    "name_ru": "Акалтын",
                },
                {
                    "id": "60",
                    "name_uz": "Oltinkoʻl",
                    "name_oz": "Олтинкул",
                    "name_ru": "Алтынкуль",
                },
                {
                    "id": "61",
                    "name_uz": "Asaka",
                    "name_oz": "Асака",
                    "name_ru": "Асака",
                },
                {
                    "id": "62",
                    "name_uz": "Oxunboboyev",
                    "name_oz": "Охунбобоев",
                    "name_ru": "Ахунбабаев",
                },
                {
                    "id": "63",
                    "name_uz": "Baliqchi",
                    "name_oz": "Баликчи",
                    "name_ru": "Балыкчи",
                },
                {
                    "id": "64",
                    "name_uz": "Boʻz",
                    "name_oz": "Буз",
                    "name_ru": "Боз",
                },
                {
                    "id": "65",
                    "name_uz": "Buloqboshi",
                    "name_oz": "Булокбоши",
                    "name_ru": "Булакбаши",
                },

                {
                    "id": "66",
                    "name_uz": "Qorasuv",
                    "name_oz": "Корасув",
                    "name_ru": "Карасу",
                },
                {
                    "id": "67",
                    "name_uz": "Kuyganyor",
                    "name_oz": "Куйганер",
                    "name_ru": "Куйганъяр",
                },
                {
                    "id": "68",
                    "name_uz": "Qo'rg'ontepa",
                    "name_oz": "Кургонтепа",
                    "name_ru": "Кургантепа",
                },
                {
                    "id": "69",
                    "name_uz": "Marhamat",
                    "name_oz": "Мархамат",
                    "name_ru": "Мархамат",
                },
                {
                    "id": "70",
                    "name_uz": "Poytug'",
                    "name_oz": "Пойтуг",
                    "name_ru": "Пайтуг",
                },
                {
                    "id": "71",
                    "name_uz": "Paxtaobod",
                    "name_oz": "Пахтаобод",
                    "name_ru": "Пахтаабад",
                },
                {
                    "id": "72",
                    "name_uz": "Shahrixon",
                    "name_oz": "Шахрихон",
                    "name_ru": "Шахрихан",
                },
                {
                    "id": "73",
                    "name_uz": "Xonobod",
                    "name_oz": "Хонобод",
                    "name_ru": "Ханабад",
                },
                {
                    "id": "74",
                    "name_uz": "Xo'jaobod",
                    "name_oz": "Хужаобод",
                    "name_ru": "Ходжаабад",
                },

            ],
            "buhara": [
                {
                    "id": "75",
                    "name_uz": "Buxoro",
                    "name_oz": "Бухара",
                    "name_ru": "Бухара",
                },
                {
                    "id": "76",
                    "name_uz": "Olot",
                    "name_oz": "Алат",
                    "name_ru": "Алат",
                },
                {
                    "id": "77",
                    "name_uz": "Galaosiyo",
                    "name_oz": "Галаасия",
                    "name_ru": "Галаасия",
                },
                {
                    "id": "78",
                    "name_uz": "Gazli",
                    "name_oz": "Газли",
                    "name_ru": "Газли",
                },
                {
                    "id": "79",
                    "name_uz": "G'ijduvon",
                    "name_oz": "Гиждуван",
                    "name_ru": "Гиждуван",
                },
                {
                    "id": "80",
                    "name_uz": "Kogon",
                    "name_oz": "Каган",
                    "name_ru": "Каган",
                },
                {
                    "id": "81",
                    "name_uz": "Qorako'l",
                    "name_oz": "Каракуль",
                    "name_ru": "Каракуль",
                },
                {
                    "id": "82",
                    "name_uz": "Qorovulbozor",
                    "name_oz": "Караулбазар",
                    "name_ru": "Караулбазар",
                },

                {
                    "id": "83",
                    "name_uz": "Romitan",
                    "name_oz": "Ромитан",
                    "name_ru": "Ромитан",
                },
                {
                    "id": "84",
                    "name_uz": "Shofirkon",
                    "name_oz": "Шафиркан",
                    "name_ru": "Шафиркан",
                },
                {
                    "id": "85",
                    "name_uz": "Vobkent",
                    "name_oz": "Вабкент",
                    "name_ru": "Вабкент",
                },
                {
                    "id": "86",
                    "name_uz": "Jondor",
                    "name_oz": "Жондор",
                    "name_ru": "Жондор",
                },
            ],
            "jizzakh": [
                {
                    "id": "87",
                    "name_uz": "Jizzax",
                    "name_oz": "Джизак",
                    "name_ru": "Джизак",
                },
                {
                    "id": "88",
                    "name_uz": "Aydarko'l",
                    "name_oz": "Айдаркуль",
                    "name_ru": "Айдаркуль",
                },
                {
                    "id": "89",
                    "name_uz": "Balandchaqir",
                    "name_oz": "Баландчакир",
                    "name_ru": "Баландчакир",
                },
                {
                    "id": "90",
                    "name_uz": "Dashtobod",
                    "name_oz": "Даштобод",
                    "name_ru": "Даштобод",
                },
                {
                    "id": "91",
                    "name_uz": "Do'stlik",
                    "name_oz": "Дустлик",
                    "name_ru": "Дустлик",
                },
                {
                    "id": "92",
                    "name_uz": "Gagarin",
                    "name_oz": "Гагарин",
                    "name_ru": "Гагарин",
                },
                {
                    "id": "93",
                    "name_uz": "G'allaorol",
                    "name_oz": "Галлаарал",
                    "name_ru": "Галлаарал",
                },
                {
                    "id": "94",
                    "name_uz": "G'oliblar",
                    "name_oz": "Голиблар",
                    "name_ru": "Голиблар",
                },

                {
                    "id": "95",
                    "name_uz": "Marjonbuloq",
                    "name_oz": "Марджанбулак",
                    "name_ru": "Марджанбулак",
                },
                {
                    "id": "96",
                    "name_uz": "Paxtakor",
                    "name_oz": "Пахтакор",
                    "name_ru": "Пахтакор",
                },
                {
                    "id": "97",
                    "name_uz": "Uchtepa",
                    "name_oz": "Учтепа",
                    "name_ru": "Учтепа",
                },
                {
                    "id": "98",
                    "name_uz": "O'smat",
                    "name_oz": "Усмат",
                    "name_ru": "Усмат",
                },
                {
                    "id": "99",
                    "name_uz": "Yangiqishloq'",
                    "name_oz": "Янгикишлак",
                    "name_ru": "Янгикишлак",
                },
                {
                    "id": "100",
                    "name_uz": "Zomin",
                    "name_oz": "Заамин",
                    "name_ru": "Заамин",
                },
                {
                    "id": "101",
                    "name_uz": "Zafarobod",
                    "name_oz": "Зафарабад",
                    "name_ru": "Зафарабад",
                },
                {
                    "id": "102",
                    "name_uz": "Zarbdor",
                    "name_oz": "Зарбдар",
                    "name_ru": "Зарбдар",
                },
            ],
            "karakalpakstan": [
                {
                    "id": "103",
                    "name_uz": "Nukus",
                    "name_oz": "Нукус",
                    "name_ru": "Нукус",
                },
                {
                    "id": "104",
                    "name_uz": "Oqmangʻit",
                    "name_oz": "Акмангит",
                    "name_ru": "Акмангит",
                },
                {
                    "id": "105",
                    "name_uz": "Beruniy",
                    "name_oz": "Беруни",
                    "name_ru": "Беруни",
                },
                {
                    "id": "106",
                    "name_uz": "Bo'ston",
                    "name_oz": "Бустан",
                    "name_ru": "Бустан",
                },
                {
                    "id": "107",
                    "name_uz": "Chimboy",
                    "name_oz": "Чимбай",
                    "name_ru": "Чимбай",
                },
                {
                    "id": "108",
                    "name_uz": "Qanlikoʻl",
                    "name_oz": "Канлыкуль",
                    "name_ru": "Канлыкуль",
                },
                {
                    "id": "109",
                    "name_uz": "Qoraoʻzak",
                    "name_oz": "Караузяк",
                    "name_ru": "Караузяк",
                },
                {
                    "id": "110",
                    "name_uz": "Kegeyli",
                    "name_oz": "Кегейли",
                    "name_ru": "Кегейли",
                },

                {
                    "id": "111",
                    "name_uz": "Qo'ng'irot",
                    "name_oz": "Кунград",
                    "name_ru": "Кунград",
                },
                {
                    "id": "112",
                    "name_uz": "Mang'it",
                    "name_oz": "Мангит",
                    "name_ru": "Мангит",
                },
                {
                    "id": "113",
                    "name_uz": "Mo'ynoq",
                    "name_oz": "Муйнак",
                    "name_ru": "Муйнак",
                },
                {
                    "id": "114",
                    "name_uz": "Shumanay",
                    "name_oz": "Шуманай",
                    "name_ru": "Шуманай",
                },
                {
                    "id": "115",
                    "name_uz": "Taxiatosh'",
                    "name_oz": "Тахиаташ",
                    "name_ru": "Тахиаташ",
                },
                {
                    "id": "116",
                    "name_uz": "Taxtakoʻpir",
                    "name_oz": "Тахтакупыр",
                    "name_ru": "Тахтакупыр",
                },
                {
                    "id": "117",
                    "name_uz": "To'rtko'l",
                    "name_oz": "Турткуль",
                    "name_ru": "Турткуль",
                },
                {

                    "id": "118",
                    "name_uz": "Xo'jayli",
                    "name_oz": "Ходжейли",
                    "name_ru": "Ходжейли",
                },
            ],
            "kashkadarya": [
                {
                    "id": "119",
                    "name_uz": "Qarshi",
                    "name_oz": "Карши",
                    "name_ru": "Карши",
                },
                {
                    "id": "120",
                    "name_uz": "Beshkent",
                    "name_oz": "Бешкент",
                    "name_ru": "Бешкент",
                },
                {
                    "id": "121",
                    "name_uz": "Chiroqchi",
                    "name_oz": "Чирокчи",
                    "name_ru": "Чиракчи",
                },
                {
                    "id": "122",
                    "name_uz": "Dehqonobod",
                    "name_oz": "Дехканобод",
                    "name_ru": "Дехканабад",
                },
                {
                    "id": "123",
                    "name_uz": "G'uzor",
                    "name_oz": "Гузор",
                    "name_ru": "Гузар",
                },
                {
                    "id": "124",
                    "name_uz": "Qamashi",
                    "name_oz": "Камаши",
                    "name_ru": "Камаши",
                },
                {
                    "id": "125",
                    "name_uz": "Karashina",
                    "name_oz": "Карашина",
                    "name_ru": "Карашина",
                },
                {
                    "id": "126",
                    "name_uz": "Koson",
                    "name_oz": "Косон",
                    "name_ru": "Касан",
                },

                {
                    "id": "127",
                    "name_uz": "Kasbi",
                    "name_oz": "Касби",
                    "name_ru": "Касби",
                },
                {
                    "id": "128",
                    "name_uz": "Kitob",
                    "name_oz": "Китоб",
                    "name_ru": "Китаб",
                },
                {
                    "id": "129",
                    "name_uz": "Muborak",
                    "name_oz": "Муборак",
                    "name_ru": "Мубарек",
                },
                {
                    "id": "130",
                    "name_uz": "Mugʻlon",
                    "name_oz": "Муглон",
                    "name_ru": "Муглан",
                },
                {
                    "id": "131",
                    "name_uz": "Shahrisabz'",
                    "name_oz": "Шахрисабз",
                    "name_ru": "Шахрисабз",
                },
                {
                    "id": "132",
                    "name_uz": "Talimarjon",
                    "name_oz": "Талимаржон",
                    "name_ru": "Талимарджан",
                },
                {
                    "id": "133",
                    "name_uz": "Yakkabog'",
                    "name_oz": "Яккабог",
                    "name_ru": "Яккабаг",
                },
                {
                    "id": "134",
                    "name_uz": "Mirishkor",
                    "name_oz": "Миришкор",
                    "name_ru": "Миришкор",
                },
                {

                    "id": "135",
                    "name_uz": "Nishon",
                    "name_oz": "Нишон",
                    "name_ru": "Нишан",
                },

            ],
            "navai": [
                {
                    "id": "136",
                    "name_uz": "Navoiy",
                    "name_oz": "Навои",
                    "name_ru": "Навои",
                },
                {
                    "id": "137",
                    "name_uz": "Beshrobot",
                    "name_oz": "Бешработ",
                    "name_ru": "Бешрабат",
                },
                {
                    "id": "138",
                    "name_uz": "Konimex",
                    "name_oz": "Конимех",
                    "name_ru": "Канимех",
                },
                {
                    "id": "139",
                    "name_uz": "Karmana",
                    "name_oz": "Кармана",
                    "name_ru": "Кармана",
                },
                {
                    "id": "140",
                    "name_uz": "Qiziltepa",
                    "name_oz": "Кизилтепа",
                    "name_ru": "Кызылтепа",
                },
                {
                    "id": "141",
                    "name_uz": "Nurota",
                    "name_oz": "Нурота",
                    "name_ru": "Нурата",
                },
                {
                    "id": "142",
                    "name_uz": "Tomdibuloq",
                    "name_oz": "Томдибулок",
                    "name_ru": "Тамдыбулак",
                },
                {
                    "id": "143",
                    "name_uz": "Uchquduq",
                    "name_oz": "Учкудук",
                    "name_ru": "Учкудук",
                },

                {
                    "id": "144",
                    "name_uz": "Yangirobot",
                    "name_oz": "Янгиработ",
                    "name_ru": "Янгирабат",
                },
                {
                    "id": "145",
                    "name_uz": "Zarafshon",
                    "name_oz": "Зарафшон",
                    "name_ru": "Зарафшан",
                },

            ],
            "namangan": [
                {
                    "id": "146",
                    "name_uz": "Namangan",
                    "name_oz": "Наманган",
                    "name_ru": "Наманган",
                },
                {
                    "id": "147",
                    "name_uz": "Chortoq",
                    "name_oz": "Чартак",
                    "name_ru": "Чартак",
                },
                {
                    "id": "148",
                    "name_uz": "Chust",
                    "name_oz": "Чуст",
                    "name_ru": "Чуст",
                },
                {
                    "id": "149",
                    "name_uz": "Jomashoʻy",
                    "name_oz": "Джумашуй",
                    "name_ru": "Джумашуй",
                },
                {
                    "id": "150",
                    "name_uz": "Kosonsoy",
                    "name_oz": "Касансай",
                    "name_ru": "Касансай",
                },
                {
                    "id": "151",
                    "name_uz": "Pop",
                    "name_oz": "Поп",
                    "name_ru": "Пап",
                },
                {
                    "id": "152",
                    "name_uz": "Toshbuloq",
                    "name_oz": "Тошбулок",
                    "name_ru": "Ташбулак",
                },

                {
                    "id": "153",
                    "name_uz": "To'raqo'rg'on",
                    "name_oz": "Туракургон",
                    "name_ru": "Туракурган",
                },
                {
                    "id": "154",
                    "name_uz": "Uchqo'rg'on",
                    "name_oz": "Учкурган",
                    "name_ru": "Учкурган",
                },
                {
                    "id": "155",
                    "name_uz": "Xaqqulobod",
                    "name_oz": "Хаккулабад",
                    "name_ru": "Хаккулабад",
                },

            ],
            "surkhandarya": [
                {
                    "id": "156",
                    "name_uz": "Termiz",
                    "name_oz": "Термиз",
                    "name_ru": "Термез",
                },
                {
                    "id": "157",
                    "name_uz": "Angor",
                    "name_oz": "Ангор",
                    "name_ru": "Ангор",
                },
                {
                    "id": "158",
                    "name_uz": "Boysun",
                    "name_oz": "Бойсун",
                    "name_ru": "Байсун",
                },
                {
                    "id": "159",
                    "name_uz": "Bandixon",
                    "name_oz": "Бандихон",
                    "name_ru": "Бандихон",
                },
                {
                    "id": "160",
                    "name_uz": "Denov",
                    "name_oz": "Денов",
                    "name_ru": "Денау",
                },
                {
                    "id": "161",
                    "name_uz": "Jarqo'rg'on",
                    "name_oz": "Жаркургон",
                    "name_ru": "Джаркурган",
                },
                {
                    "id": "162",
                    "name_uz": "Qorlik",
                    "name_oz": "Корлик",
                    "name_ru": "Карлук",
                },
                {
                    "id": "163",
                    "name_uz": "Qiziriq",
                    "name_oz": "Кизирик",
                    "name_ru": "Кизирик",
                },

                {
                    "id": "164",
                    "name_uz": "Qumqo'rg'on",
                    "name_oz": "Кумкургон",
                    "name_ru": "Кумкурган",
                },
                {
                    "id": "165",
                    "name_uz": "Muzrobod",
                    "name_oz": "Музробод",
                    "name_ru": "Музрабад",
                },
                {
                    "id": "166",
                    "name_uz": "Sariosiyo",
                    "name_oz": "Сариосие",
                    "name_ru": "Сариасия",
                },
                {
                    "id": "167",
                    "name_uz": "Sariq",
                    "name_oz": "Сарик",
                    "name_ru": "Сарык",
                },
                {
                    "id": "168",
                    "name_uz": "Sharg'un'",
                    "name_oz": "Шаргун",
                    "name_ru": "Шаргунь",
                },
                {
                    "id": "169",
                    "name_uz": "Sherobod",
                    "name_oz": "Шеробод",
                    "name_ru": "Шерабад",
                },
                {
                    "id": "170",
                    "name_uz": "Sho'rchi",
                    "name_oz": "Шурчи",
                    "name_ru": "Шурчи",
                },
                {
                    "id": "171",
                    "name_uz": "Uchqizil",
                    "name_oz": "Учкизил",
                    "name_ru": "Учкызыл",
                },
                {
                    "id": "172",
                    "name_uz": "Uzun",
                    "name_oz": "Узун",
                    "name_ru": "Узун",
                },
                {
                    "id": "173",
                    "name_uz": "Xalqobod",
                    "name_oz": "Халкобод",
                    "name_ru": "Халкабад",
                },

            ],
            "sirdarya": [
                {
                    "id": "174",
                    "name_uz": "Guliston",
                    "name_oz": "Гулистан",
                    "name_ru": "Гулистан",
                },
                {
                    "id": "175",
                    "name_uz": "Sirdaryo",
                    "name_oz": "Cырдарья",
                    "name_ru": "Cырдарья",
                },
                {
                    "id": "176",
                    "name_uz": "Baxt",
                    "name_oz": "Бахт",
                    "name_ru": "Бахт",
                },
                {
                    "id": "177",
                    "name_uz": "Boyovut",
                    "name_oz": "Баяут",
                    "name_ru": "Баяут",
                },
                {
                    "id": "178",
                    "name_uz": "Navroʻz",
                    "name_oz": "Навруз",
                    "name_ru": "Навруз",
                },
                {
                    "id": "179",
                    "name_uz": "Sayxun",
                    "name_oz": "Сайхун",
                    "name_ru": "Сайхун",
                },
                {
                    "id": "180",
                    "name_uz": "Sardoba",
                    "name_oz": "Сардоба",
                    "name_ru": "Сардоба",
                },
                {
                    "id": "181",
                    "name_uz": "Shirin",
                    "name_oz": "Ширин",
                    "name_ru": "Ширин",
                },
                {
                    "id": "182",
                    "name_uz": "Terenozek",
                    "name_oz": "Теренозек",
                    "name_ru": "Теренозек",
                },

                {
                    "id": "183",
                    "name_uz": "Xovos",
                    "name_oz": "Ховос",
                    "name_ru": "Хаваст",
                },
                {
                    "id": "184",
                    "name_uz": "Yangiyer",
                    "name_oz": "Янгиер",
                    "name_ru": "Янгиер",
                },



            ],
            "fergana": [
                {
                    "id": "185",
                    "name_uz": "Farg‘ona",
                    "name_oz": "Фаргона",
                    "name_ru": "Фергана",
                },
                {
                    "id": "186",
                    "name_uz": "Oltiariq",
                    "name_oz": "Олтиарик",
                    "name_ru": "Алтыарык",
                },
                {
                    "id": "187",
                    "name_uz": "Bogʻdod",
                    "name_oz": "Богдод",
                    "name_ru": "Багдад",
                },
                {
                    "id": "188",
                    "name_uz": "Beshariq",
                    "name_oz": "Бешарик",
                    "name_ru": "Бешарык",
                },
                {
                    "id": "189",
                    "name_uz": "Dangʻara",
                    "name_oz": "Дангара",
                    "name_ru": "Дангара",
                },
                {
                    "id": "190",
                    "name_uz": "Qo'qon",
                    "name_oz": "Кукон",
                    "name_ru": "Коканд",
                },
                {
                    "id": "191",
                    "name_uz": "Quva",
                    "name_oz": "Кува",
                    "name_ru": "Кува",
                },
                {
                    "id": "192",
                    "name_uz": "Quvasoy",
                    "name_oz": "Кувасой",
                    "name_ru": "Кувасай",
                },

                {
                    "id": "193",
                    "name_uz": "Langar",
                    "name_oz": "Лангар",
                    "name_ru": "Лангар",
                },
                {
                    "id": "194",
                    "name_uz": "Marg'ilon",
                    "name_oz": "Маргилон",
                    "name_ru": "Маргилан",
                },
                {
                    "id": "195",
                    "name_uz": "Navbahor",
                    "name_oz": "Навбахор",
                    "name_ru": "Навбахор",
                },
                {
                    "id": "196",
                    "name_uz": "Ravon",
                    "name_oz": "Равон",
                    "name_ru": "Раван",
                },
                {
                    "id": "197",
                    "name_uz": "Rishton",
                    "name_oz": "Риштон",
                    "name_ru": "Риштан",
                },
                {
                    "id": "198",
                    "name_uz": "Shohimardon",
                    "name_oz": "Шохимардон",
                    "name_ru": "Шахимардан",
                },
                {
                    "id": "199",
                    "name_uz": "Toshloq",
                    "name_oz": "Тошлок",
                    "name_ru": "Ташлак",
                },
                {
                    "id": "200",
                    "name_uz": "Uchkoʻpriq",
                    "name_oz": "Учкуприк",
                    "name_ru": "Учкуприк",
                },
                {
                    "id": "201",
                    "name_uz": "Vodil",
                    "name_oz": "Водил",
                    "name_ru": "Вуадиль",
                },
                {
                    "id": "202",
                    "name_uz": "Hamza",
                    "name_oz": "Хамза",
                    "name_ru": "Хамза",
                },
                {
                    "id": "203",
                    "name_uz": "Yaypan",
                    "name_oz": "Яйпан",
                    "name_ru": "Яйпан",
                },
                {
                    "id": "204",
                    "name_uz": "Yangi Margʻilon",
                    "name_oz": "Янги Маргилон",
                    "name_ru": "Янги Маргилан",
                },
                {
                    "id": "205",
                    "name_uz": "Yangiqoʻrgʻon",
                    "name_oz": "Янгикургон",
                    "name_ru": "Янгикурган",
                },
                {
                    "id": "206",
                    "name_uz": "Yozyovon",
                    "name_oz": "Езевон",
                    "name_ru": "Язъяван",
                },

            ],
            "khorezm": [
                {
                    "id": "207",
                    "name_uz": "Urganch",
                    "name_oz": "Урганч",
                    "name_ru": "Ургенч",
                },
                {
                    "id": "208",
                    "name_uz": "Bog'ot",
                    "name_oz": "Богот",
                    "name_ru": "Багат",
                },
                {
                    "id": "209",
                    "name_uz": "Cholish",
                    "name_oz": "Чолиш",
                    "name_ru": "Чалыш",
                },
                {
                    "id": "210",
                    "name_uz": "Gurlan",
                    "name_oz": "Гурлан",
                    "name_ru": "Гурлен",
                },
                {
                    "id": "211",
                    "name_uz": "Qorovul",
                    "name_oz": "Коровул",
                    "name_ru": "Караул",
                },
                {
                    "id": "212",
                    "name_uz": "Qoʻshkoʻpir",
                    "name_oz": "Кушкупир",
                    "name_ru": "Кошкупыр",
                },
                {
                    "id": "213",
                    "name_uz": "Pitnak",
                    "name_oz": "Питнак",
                    "name_ru": "Питнак",
                },
                {
                    "id": "214",
                    "name_uz": "Shovot",
                    "name_oz": "Шовот",
                    "name_ru": "Шават",
                },

                {
                    "id": "215",
                    "name_uz": "Xonqa",
                    "name_oz": "Хонка",
                    "name_ru": "Ханка",
                },
                {
                    "id": "216",
                    "name_uz": "Xozarasp",
                    "name_oz": "Хазорасп",
                    "name_ru": "Хазарасп",
                },
                {
                    "id": "217",
                    "name_uz": "Xiva",
                    "name_oz": "Хива",
                    "name_ru": "Хива",
                },
                {
                    "id": "218",
                    "name_uz": "Yangiariq",
                    "name_oz": "Янгиарик",
                    "name_ru": "Янгиарык",
                },

            ],
        }
    ]

export default location;